### ISSUE TITLE
通过python，单独运行miyoubi_task.py失败

### ISSUE THREAD

**Issue by lingkawaii** [Yoimiya-993/Miyoushe-Auto#1]
我想在青龙上进行计划执行，但是好像缺了一个模块包，通过依赖安装失败。
运行日志：
## 开始执行... 2024-01-28 10:22:21

Traceback (most recent call last):
  File "/ql/data/scripts/Yoimiya-993_Miyoushe-Auto/miyoubi_task.py", line 5, in <module>
    from login_miyoushe import main as login_account
ModuleNotFoundError: No module named 'login_miyoushe'

## 执行结束... 2024-01-28 10:22:22  耗时 1 秒　　
大佬能否提供这个模块包呢！

**Comment by Yoimiya-993** [comment]
我把login_miyoushe模块改名为add_account了，miyoubi_task.py里的代码也改了，只是没有推送过来

**Comment by Yoimiya-993** [comment]
最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE(Pycharm)进行git代码推送一直失败，你知道怎么解决吗
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/52495231/0a54e8ad-b7d9-411d-aea2-0e33f2aa922f)

**Comment by lingkawaii** [comment]
> 我把login_miyoushe模块改名为add_account了，miyoubi_task.py里的代码也改了，只是没有推送过来

我把模块注释了，可以正常运行！
日志：
## 开始执行... 2024-01-28 11:05:30

2024-01-28 11:05:30,731 [INFO] miyoubi_task.load_user: 正在读取“user_info”文件...
2024-01-28 11:05:30,732 [INFO] miyoubi_task.load_user: “user_info”文件读取完毕，共有1个账号！

2024-01-28 11:05:31,733 [INFO] miyoubi_task.do_myb_task: 开始执行米游币任务...

2024-01-28 11:05:32,734 [WARNING] miyoubi_task.do_myb_task: ==开始第1个账号的米游币任务==
2024-01-28 11:05:33,113 [INFO] miyoubi_task.verifyStoken: 正在验证用户[lingkawaii]的登录状态...
2024-01-28 11:05:33,399 [INFO] miyoubi_task.verifyStoken: [lingkawaii]的登录状态正常！
2024-01-28 11:05:33,401 [INFO] miyoubi_task.getArticleList: 正在获取5个【大别野】的帖子...
2024-01-28 11:05:34,022 [INFO] miyoubi_task.getArticleList: 获取成功！
2024-01-28 11:05:36,026 [INFO] miyoubi_task.readArticle: 正在看帖...
2024-01-28 11:05:36,440 [INFO] miyoubi_task.readArticle: 看帖《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！
2024-01-28 11:05:38,874 [INFO] miyoubi_task.readArticle: 看帖《(二十九)中药:核桃仁(补虚药)》成功！
2024-01-28 11:05:41,292 [INFO] miyoubi_task.readArticle: 看帖《240128氵》成功！
2024-01-28 11:05:43,295 [INFO] miyoubi_task.upVote: 正在点赞...
2024-01-28 11:05:43,713 [INFO] miyoubi_task.upVote: 点赞《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！
2024-01-28 11:05:46,089 [INFO] miyoubi_task.upVote: 点赞《(二十九)中药:核桃仁(补虚药)》成功！
2024-01-28 11:05:48,455 [INFO] miyoubi_task.upVote: 点赞《240128氵》成功！
2024-01-28 11:05:51,007 [INFO] miyoubi_task.upVote: 点赞《秩序，不可破。》成功！
2024-01-28 11:05:53,441 [INFO] miyoubi_task.upVote: 点赞《听》成功！
2024-01-28 11:05:55,444 [INFO] miyoubi_task.share: 正在分享...
2024-01-28 11:05:55,799 [INFO] miyoubi_task.share: 分享《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！
2024-01-28 11:05:57,802 [INFO] miyoubi_task.signIn: 正在打卡...
2024-01-28 11:05:58,314 [ERROR] miyoubi_task.signIn: 【大别野】打卡失败，原因：签到失败或重复签到


## 执行结束... 2024-01-28 11:05:59  耗时 29 秒

**Comment by lingkawaii** [comment]
> 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE（Pycharm）进行git代码推送一直失败，你知道怎么解决吗 ![图像](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE0MzYsIm5iZiI6MTcwNjQxMTEzNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwN2JkMWQyNTg0MDk1YjI2YWNmNWFhNzIyOTkyMTMwN2QyN2RlZDRiNmYyZTU0YmJjM2M2OWIxOGM5ZGJmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb2EQv7caFfizv4lQyDA2yycvUObpwR9n1AkGYdvU4c)

试试改host？

**Comment by Yoimiya-993** [comment]
> > 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE（Pycharm）进行git代码推送一直失败，你知道怎么解决吗 ![图像](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE0MzYsIm5iZiI6MTcwNjQxMTEzNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwN2JkMWQyNTg0MDk1YjI2YWNmNWFhNzIyOTkyMTMwN2QyN2RlZDRiNmYyZTU0YmJjM2M2OWIxOGM5ZGJmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb2EQv7caFfizv4lQyDA2yycvUObpwR9n1AkGYdvU4c)
> 
> 试试改host？

host试过没用才开的梯子

> > 我把login_miyoushe模块改名为add_account了，miyoubi_task.py里的代码也改了，只是没有推送过来
> 
> 我把模块注释了，可以正常运行！ 日志：
> 
> ## 开始执行... 2024-01-28 11:05:30
> 2024-01-28 11:05:30,731 [INFO] miyoubi_task.load_user: 正在读取“user_info”文件... 2024-01-28 11:05:30,732 [INFO] miyoubi_task.load_user: “user_info”文件读取完毕，共有1个账号！
> 
> 2024-01-28 11:05:31,733 [INFO] miyoubi_task.do_myb_task: 开始执行米游币任务...
> 
> 2024-01-28 11:05:32,734 [WARNING] miyoubi_task.do_myb_task: ==开始第1个账号的米游币任务== 2024-01-28 11:05:33,113 [INFO] miyoubi_task.verifyStoken: 正在验证用户[lingkawaii]的登录状态... 2024-01-28 11:05:33,399 [INFO] miyoubi_task.verifyStoken: [lingkawaii]的登录状态正常！ 2024-01-28 11:05:33,401 [INFO] miyoubi_task.getArticleList: 正在获取5个【大别野】的帖子... 2024-01-28 11:05:34,022 [INFO] miyoubi_task.getArticleList: 获取成功！ 2024-01-28 11:05:36,026 [INFO] miyoubi_task.readArticle: 正在看帖... 2024-01-28 11:05:36,440 [INFO] miyoubi_task.readArticle: 看帖《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:38,874 [INFO] miyoubi_task.readArticle: 看帖《(二十九)中药:核桃仁(补虚药)》成功！ 2024-01-28 11:05:41,292 [INFO] miyoubi_task.readArticle: 看帖《240128氵》成功！ 2024-01-28 11:05:43,295 [INFO] miyoubi_task.upVote: 正在点赞... 2024-01-28 11:05:43,713 [INFO] miyoubi_task.upVote: 点赞《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:46,089 [INFO] miyoubi_task.upVote: 点赞《(二十九)中药:核桃仁(补虚药)》成功！ 2024-01-28 11:05:48,455 [INFO] miyoubi_task.upVote: 点赞《240128氵》成功！ 2024-01-28 11:05:51,007 [INFO] miyoubi_task.upVote: 点赞《秩序，不可破。》成功！ 2024-01-28 11:05:53,441 [INFO] miyoubi_task.upVote: 点赞《听》成功！ 2024-01-28 11:05:55,444 [INFO] miyoubi_task.share: 正在分享... 2024-01-28 11:05:55,799 [INFO] miyoubi_task.share: 分享《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:57,802 [INFO] miyoubi_task.signIn: 正在打卡... 2024-01-28 11:05:58,314 [ERROR] miyoubi_task.signIn: 【大别野】打卡失败，原因：签到失败或重复签到
> 
> ## 执行结束... 2024-01-28 11:05:59 耗时 29 秒

你运行它之前添加过账号就不会报错，这个模块导进来就是用于没有账号的情况下添加第一个账号

**Comment by Yoimiya-993** [comment]
青龙面板就是用来定时运行程序的吧，它免费吗？

**Comment by lingkawaii** [comment]
> > > 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE（Pycharm）进行git代码推送一直失败，你知道怎么解决吗 ![图像](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE0MzYsIm5iZiI6MTcwNjQxMTEzNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwN2JkMWQyNTg0MDk1YjI2YWNmNWFhNzIyOTkyMTMwN2QyN2RlZDRiNmYyZTU0YmJjM2M2OWIxOGM5ZGJmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb2EQv7caFfizv4lQyDA2yycvUObpwR9n1AkGYdvU4c)
> > 
> > 
> > 试试改host？
> 
> host试过没用才开的梯子
> 
> > > 我把login_miyoushe模块改名为add_account了，miyoubi_task.py里的代码也改了，只是没有推送过来
> > 
> > 
> > 我把模块注释了，可以正常运行！ 日志：
> > ## 开始执行... 2024-01-28 11:05:30
> > 2024-01-28 11:05:30,731 [INFO] miyoubi_task.load_user: 正在读取“user_info”文件... 2024-01-28 11:05:30,732 [INFO] miyoubi_task.load_user: “user_info”文件读取完毕，共有1个账号！
> > 2024-01-28 11:05:31,733 [INFO] miyoubi_task.do_myb_task: 开始执行米游币任务...
> > 2024-01-28 11:05:32,734 [WARNING] miyoubi_task.do_myb_task: ==开始第1个账号的米游币任务== 2024-01-28 11:05:33,113 [INFO] miyoubi_task.verifyStoken: 正在验证用户[lingkawaii]的登录状态... 2024-01-28 11:05:33,399 [INFO] miyoubi_task.verifyStoken: [lingkawaii]的登录状态正常！ 2024-01-28 11:05:33,401 [INFO] miyoubi_task.getArticleList: 正在获取5个【大别野】的帖子... 2024-01-28 11:05:34,022 [INFO] miyoubi_task.getArticleList: 获取成功！ 2024-01-28 11:05:36,026 [INFO] miyoubi_task.readArticle: 正在看帖... 2024-01-28 11:05:36,440 [INFO] miyoubi_task.readArticle: 看帖《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:38,874 [INFO] miyoubi_task.readArticle: 看帖《(二十九)中药:核桃仁(补虚药)》成功！ 2024-01-28 11:05:41,292 [INFO] miyoubi_task.readArticle: 看帖《240128氵》成功！ 2024-01-28 11:05:43,295 [INFO] miyoubi_task.upVote: 正在点赞... 2024-01-28 11:05:43,713 [INFO] miyoubi_task.upVote: 点赞《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:46,089 [INFO] miyoubi_task.upVote: 点赞《(二十九)中药:核桃仁(补虚药)》成功！ 2024-01-28 11:05:48,455 [INFO] miyoubi_task.upVote: 点赞《240128氵》成功！ 2024-01-28 11:05:51,007 [INFO] miyoubi_task.upVote: 点赞《秩序，不可破。》成功！ 2024-01-28 11:05:53,441 [INFO] miyoubi_task.upVote: 点赞《听》成功！ 2024-01-28 11:05:55,444 [INFO] miyoubi_task.share: 正在分享... 2024-01-28 11:05:55,799 [INFO] miyoubi_task.share: 分享《身为主角的我居然死而复生了！王样战队君王者第十一集解说【上】》成功！ 2024-01-28 11:05:57,802 [INFO] miyoubi_task.signIn: 正在打卡... 2024-01-28 11:05:58,314 [ERROR] miyoubi_task.signIn: 【大别野】打卡失败，原因：签到失败或重复签到
> > ## 执行结束... 2024-01-28 11:05:59 耗时 29 秒
> 
> 你运行它之前添加过账号就不会报错，这个模块导进来就是用于没有账号的情况下添加第一个账号

是的，我在运行前，在我的windows上单独运行了打包的程序，然后把那个user_info.json一起复制过去了！

**Comment by lingkawaii** [comment]
> 青龙面板就是用来定时运行程序的吧，它免费吗？
免费的，这个是项目地址https://github.com/whyour/qinglong

**Comment by lingkawaii** [comment]
> 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE(Pycharm)进行git代码推送一直失败，你知道怎么解决吗 ![image](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE5MTYsIm5iZiI6MTcwNjQxMTYxNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzZlMTgzYzEzOWE1OTliODkwYzhmZjRjM2JmNmI4NzliZGE2ZWZjYjE0OTc3NjRiYzQ4YTUyM2QwYjg1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XnsfupmhrAjExjbqFlHnZ5C7LCmOC3J2c8fZ6Ljdb9Y)

![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/20828928/c47fe768-442e-4264-873a-cb59ed2b8b75)
g
我记得之前电信有概率可以直接访问的，现在全挂了！
想问一下你用的什么代理软件，一般设置系统代理，ide好像也会自动设置！

**Comment by Yoimiya-993** [comment]
> > 青龙面板就是用来定时运行程序的吧，它免费吗？
> > 免费的，这个是项目地址https://github.com/whyour/qinglong

我去了解下，谢谢

**Comment by Yoimiya-993** [comment]
> > 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE(Pycharm)进行git代码推送一直失败，你知道怎么解决吗 ![image](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE5MTYsIm5iZiI6MTcwNjQxMTYxNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzZlMTgzYzEzOWE1OTliODkwYzhmZjRjM2JmNmI4NzliZGE2ZWZjYjE0OTc3NjRiYzQ4YTUyM2QwYjg1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XnsfupmhrAjExjbqFlHnZ5C7LCmOC3J2c8fZ6Ljdb9Y)
> 
> ![image](https://private-user-images.githubusercontent.com/20828928/300232186-c47fe768-442e-4264-873a-cb59ed2b8b75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTIzMTIsIm5iZiI6MTcwNjQxMjAxMiwicGF0aCI6Ii8yMDgyODkyOC8zMDAyMzIxODYtYzQ3ZmU3NjgtNDQyZS00MjY0LTg3M2EtY2I1OWVkMmI4Yjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDc5MWI5ZDc2MzBkYjcwNTZmNjZmNGIyNThjMTkzMDU5OWU4NzQ4NjJlNmZiOTNkMDgyOTM3ZDJhYjlmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wR2aAnxj6ADxQIU8gy4aomc_opOoM6qXxrowJXzWZvc) g 我记得之前电信有概率可以直接访问的，现在全挂了！ 想问一下你用的什么代理软件，一般设置系统代理，ide好像也会自动设置！

v2rayN+GitHub上找的免费节点，是开的系统代理
图上这个是什么网站/工具？

**Comment by lingkawaii** [comment]
> > > 最近我用GitHub出问题了，开梯子浏览器才能访问GitHub，但是我开发用的IDE(Pycharm)进行git代码推送一直失败，你知道怎么解决吗 ![image](https://private-user-images.githubusercontent.com/52495231/300231791-0a54e8ad-b7d9-411d-aea2-0e33f2aa922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTE5MTYsIm5iZiI6MTcwNjQxMTYxNiwicGF0aCI6Ii81MjQ5NTIzMS8zMDAyMzE3OTEtMGE1NGU4YWQtYjdkOS00MTFkLWFlYTItMGUzM2YyYWE5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzZlMTgzYzEzOWE1OTliODkwYzhmZjRjM2JmNmI4NzliZGE2ZWZjYjE0OTc3NjRiYzQ4YTUyM2QwYjg1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XnsfupmhrAjExjbqFlHnZ5C7LCmOC3J2c8fZ6Ljdb9Y)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/20828928/300232186-c47fe768-442e-4264-873a-cb59ed2b8b75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTIzMTIsIm5iZiI6MTcwNjQxMjAxMiwicGF0aCI6Ii8yMDgyODkyOC8zMDAyMzIxODYtYzQ3ZmU3NjgtNDQyZS00MjY0LTg3M2EtY2I1OWVkMmI4Yjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAzMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDc5MWI5ZDc2MzBkYjcwNTZmNjZmNGIyNThjMTkzMDU5OWU4NzQ4NjJlNmZiOTNkMDgyOTM3ZDJhYjlmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wR2aAnxj6ADxQIU8gy4aomc_opOoM6qXxrowJXzWZvc) g 我记得之前电信有概率可以直接访问的，现在全挂了！ 想问一下你用的什么代理软件，一般设置系统代理，ide好像也会自动设置！
> 
> v2rayN+GitHub上找的免费节点，是开的系统代理 图上这个是什么网站/工具？

系统代理不行的话我建议使用tun模式，用管理员模式运行v2rayN就能使用tun模式了，tun模式会代理所有网络流量
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/20828928/6f78ef61-9001-4b82-adb1-d4851fbb3fb7)
提供自建一个德国节点，快过期了，不怎么用了
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogInlna2trLXZtLXdzIiwNCiAgImFkZCI6ICI0NS4xNDcuNTAuNjUiLA0KICAicG9ydCI6ICIyMDg2IiwNCiAgImlkIjogIjFlMTQ5YTljLTcxZTMtNDM4OS05Y2UzLTU3ZjJiY2Q3NDJkNiIsDQogICJhaWQiOiAiMCIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAid3d3LmJpbmcuY29tIiwNCiAgInBhdGgiOiAiMWUxNDlhOWMtNzFlMy00Mzg5LTljZTMtNTdmMmJjZDc0MmQ2LXZtIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiIsDQogICJmcCI6ICIiDQp9

工具是这个网站的https://ping.chinaz.com/，测试网站在国内的访问情况

**Comment by Yoimiya-993** [comment]
可以推送了，git要配置一下代理

**Comment by lingkawaii** [comment]
> 可以推送了，git要配置一下代理

重新拉取了，现在没有问题了，谢谢大佬！

**Comment by Yoimiya-993** [comment]
> > 可以推送了，git要配置一下代理
> 
> 重新拉取了，现在没有问题了，谢谢大佬！

不客气
