### ISSUE TITLE
[Bug] 29号起点赞请求报错

### ISSUE THREAD

**Issue by PIut02** [Yoimiya-993/Miyoushe-Auto#2]
2024-04-29 09:22:20,113 [ERROR] miyoubi_task->upVote: 点赞《今天也要加油哦》失败，原因：invalid request
2024-04-30 00:42:52,003 [ERROR] miyoubi_task->upVote: 点赞《预告！五一期间会在米游社快闪店cos阿姬捏～》失败，原因：invalid request

**Comment by Yoimiya-993** [comment]
应该是stoken过期了

**Comment by PIut02** [comment]
看了下api那边现在网页登录无法获取stoken v1的数据了，重新运行添加米游社账号任务现在无法获取正常的stoken，虽然没有报错但运行任务提示登录过期。之前获取的stoken仍然能用，看帖正常只是任务执行到点赞就报错了，不知道和这个有没有关系

**Comment by Yoimiya-993** [comment]
重新运行一遍呢

**Comment by PIut02** [comment]
米游币任务没问题了。网页登录的接口失效了https://github.com/UIGF-org/mihoyo-api-collect/issues/46 ，所以更改后的add_account.py获取的stoken和更改前获取的是一样的，均提示登录过期，但参考https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/286 中似乎使用stoken v2也能签到和米游币任务
但已经不影响使用了，感谢！

**Comment by Yoimiya-993** [comment]
扫码获取已经写好了，等我推送
