### ISSUE TITLE
求问获取账号的浏览器要求

### ISSUE THREAD

**Issue by b9735** [Yoimiya-993/Miyoushe-Auto#3]
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/78631689/9498b912-4317-4782-a4e0-f051676aa8c9)
必须是120版本的吗，感觉回退版本不是很方便

**Comment by Yoimiya-993** [comment]
遇到这个问题是去更新浏览器驱动程序msedgedriver.exe，而不是回退浏览器版本
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/52495231/3426cdde-7a8c-4a5e-84a5-17468089bcf6)
看到报错信息的这里，这是你当前浏览器版本号，去下和我框起来的这个大版本号数字一致的驱动就行了，下载地址在[这里](https://developer.microsoft.com/zh-cn/microsoft-edge/tools/webdriver/)

不过现在你不用去管它了，米哈游通行证login_ticket已经获取不到stoken，现在要用米游社扫码获取

**Comment by PIut02** [comment]
只是问浏览器要求的话下载最新的msedgedriver替换就可以了，不用回退浏览器版本
