### ISSUE TITLE
python运行求问

### ISSUE THREAD

**Issue by b9735** [Yoimiya-993/Miyoushe-Auto#4]
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/78631689/de265a52-0e9f-4718-be81-9b3940c6ced8)
为什么我导入不了request包呢，我已经导入了requests也报错，我导入http结果就导包出错了

**Comment by Yoimiya-993** [comment]
你的项目文件夹里有request.py文件吗

**Comment by yls888** [comment]
> 你的项目文件夹里有request.py文件吗

问题是您的项目里也没上传request.py呀~

**Comment by Yoimiya-993** [comment]
我丢，还真没传
