### ISSUE TITLE
不支持大于120版本的edge

### ISSUE THREAD

**Issue by Kakitoritay** [Yoimiya-993/Miyoushe-Auto#5]
![0](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/70421298/c23211be-d98d-4ab1-b515-16b1dc502311)

**Comment by Yoimiya-993** [comment]
exe是老版添加账号方式，一月份上传的，已失效
现在需要你自己克隆仓库，运行相应的Python文件
或者等我今天把新代码打包好上传
