### ISSUE TITLE
报个问题，关于启动项

### ISSUE THREAD

**Issue by geniusNFIL** [Yoimiya-993/Miyoushe-Auto#6]
我利用windows自带的自启动“计划任务”，添加每天在某个时间自动启动米游币任务exe，但是出现的是：
2024-06-26 12:23:39,020 [INFO] 正在读取“user_info”文件...
2024-06-26 12:23:39,020 [INFO] ”user_info“文件不存在，请添加一个账号以开始米游币任务
2024-06-26 12:23:39,020 [INFO] 正在生成二维码...
2024-06-26 12:23:39,285 [INFO] 打开米游社扫描出现的二维码
Nuitka: Need to use '--enable-plugin=tk-inter' option during compilation for tk-inter to work!

但是，自行双击 米游币任务exe无任何问题，请求查看问题所在

**Comment by Yoimiya-993** [comment]
先用另一个exe添加账号

**Comment by geniusNFIL** [comment]
大佬，不是账号问题。
我肯定先用另一个添加了账号信息的，添加完后，双击任务exe启动，脚本自动运行，运行完，自动结束退出框框，整个过程没问题，也就是说，账号添加了，没问题，运行没问题。但是当用计划任务启动时，就提示出现那个报错，相当于用计划任务启动后，任务exe运行过程中，无法识别到json，但是实际上json都在，没有改变。
大佬可以在电脑上试试，看看是不是这样的情况。

**Comment by Yoimiya-993** [comment]
你说的计划任务在哪添加

**Comment by geniusNFIL** [comment]
https://jingyan.baidu.com/article/b87fe19e53b2505218356896.html   这个是百度经验打开方式，因为不知道你的系统是多少，所以上了这个给你看，然后快捷方式：

**Comment by geniusNFIL** [comment]
https://jingyan.baidu.com/article/b87fe19e53b2505218356896.html 这个是百度经验打开方式，因为不知道你的系统是多少，所以上了这个给你看，然后快捷方式：在桌面按：win+R，出现  运行  ，在里面输入：taskschd.msc。这个是最快的，具体的使用方式，可以百度一下，挺简单的，类似定时自动化一样

**Comment by geniusNFIL** [comment]
https://jingyan.baidu.com/article/b87fe19e53b2505218356896.html 这个是百度经验打开方式，因为不知道你的系统是多少，所以上了这个给你看，然后快捷方式：在桌面按：win+R，出现  运行  ，在里面输入：taskschd.msc。这个是最快的，具体的使用方式，可以百度一下，挺简单的，类似定时自动化一样

**Comment by geniusNFIL** [comment]
大佬可以研究一下windows系统的自动化工具，这样，就可以实现电脑不关机的情况下，自动化完成很多事情

**Comment by Yoimiya-993** [comment]
操作那步是选启动程序把米游币任务exe添加上去吗？为啥我用这个计划任务直接闪退

**Comment by geniusNFIL** [comment]
是的，你看一下百度的教程，然后添加它进去，然后不用等到时间，旁边就有个开始，我就是点了那个，然后报错的，所以挺奇怪的，不知道为啥

**Comment by Yoimiya-993** [comment]
![image](https://github.com/Yoimiya-993/Miyoushe-Auto/assets/52495231/45c25291-e597-4f16-88fc-8fef6cce1f8f)
米游币任务exe所在文件夹路径粘贴到这里

**Comment by geniusNFIL** [comment]
额，问题出在这里吗？！卧槽！我把浏览左边的路径填了，下面的看是可选，就没管，感谢大佬！！！

**Comment by geniusNFIL** [comment]
大佬，还想问一个问题，GitHub上的……act,tion能运行exe吗

**Comment by Yoimiya-993** [comment]
不知道
